リソース管理サーバーの追加
sbgisen/resource_management_server pull request #1
Opened 2024-08-22 02:17 UTC by Leo-743

## Summary
リソース管理サーバーの作成

2024-08-23 11:00 UTC, KenyuKurimoto requested changes
一通り目を通し、気になった点をコメントしておきました。

今回は開発期間が限られている上、細かい点については教えていないので、これらに対応する必要はありませんが、GitHubでの共同開発作業においては、このようにレビュワーからコメントをもらい、それを通じて修正または議論し、最終的にメインブランチにマージしていくものを決めていくといった流れになります。参考情報と捉えていただければと思います。

2024-08-23 11:00 UTC, KenyuKurimoto commented on scripts/resource_operator.db
データベースの本体である、`*.db`ファイルはGitで管理するのは一般的ではありません。
DBのサイズが増大すると、Gitで管理するのが困難となり、またdbファイルはバイナリ形式なので、差分を閲覧することができず、Gitで管理するメリットも薄いからです。

代わりに、初期化操作のための`init_db.py`（今回の場合は`create_db.py`を作成していただいています）を用意するのが適切で、それを最初に1回だけ走らせてもらうようにREADME.mdなどで指示するのが良いです。

2024-08-23 11:00 UTC, KenyuKurimoto commented on scripts/insert_db.py
> +conn = sqlite3.connect('resource_operator.db')
このように、複数ヶ所で利用される名称をハードコーディング（文字列などを直書きすること）はソフトウェアのメンテ性・安全性の面から推奨されません。

例えば、今回の場合のようにDB初期化スクリプトがあり、DBの名称が決まっているのであれば、名称は定数として共用ファイルに定義しておくのが適切です。

```python:constants.py
RESOURCE_DB_NAME = 'resource_operator.db'
```
使うときは（ライブラリパスによって書き方は変わってきますが）例えば以下のように書けます。
```python
from constants import RESOURCE_DB_NAME
```

2024-08-23 11:00 UTC, KenyuKurimoto commented on scripts/cretae_db.py
> +import sqlite3
コマンドラインから実行するスクリプト類においては、shebangといって、ファイルの中身を実行するのがどこの何のプログラムなのかをわかるようにする先頭行に追加する慣習があります。
シェルスクリプトの場合なら
```bash
#!/bin/bash
```
Pythonなら
```python
#!/usr/bin/env python3
```
といった具合です。
これは、システムにおけるプログラムの位置を自動的に解決し、適切なインタプリタでスクリプトが実行されるようにするためです。

2024-08-23 11:00 UTC, KenyuKurimoto commented on scripts/cretae_db.py
ファイル命名についてですが、`create_db.py`よりも`setup_db.py`や`initialize_db.py`のような名称の方が「最初に一度だけ実行するスクリプトだということが明確になって良いでしょう。

2024-08-23 11:00 UTC, KenyuKurimoto commented on scripts/cretae_server.py
このファイルについては、リソース管理サーバー本体であることがわかるように、`resource_management_server.py`にするのがわかりやすいと思います。

2024-08-23 11:00 UTC, KenyuKurimoto commented on scripts/cretae_server.py
> +
リソース管理サーバーの性質を鑑みるに、サーバーを立ち上げ直したときは、各リソースの専有状態をリセットする運用となることが見込まれますので、ファイルのこのあたりにflaskサーバーで最初のリクエストが来るよりも前に実行される関数であることを示す、`@app.before_first_request`デコレータをつけた関数を作り、その中でDBの各リソースの解放を行うと良いでしょう。
```python
@app.before_first_request
def initialize():
    # すべてのリソースを解放する
```

2024-08-23 11:00 UTC, KenyuKurimoto commented on scripts/cretae_server.py
> +@app.route('/api/Registration', methods=['POST'])
エンドポイント名はすべて小文字にするのが一般的だそうです。
この下で使われているAPI名は先頭大文字で問題ありません。

2024-08-23 11:00 UTC, KenyuKurimoto commented on scripts/insert_db.py
> +conn = sqlite3.connect('resource_operator.db')
また、`*.db`ファイルを作成するときは、パスを指定してあげるのが良いでしょう。
```python
db_path = '/path/to/resource_operator.db'
conn = sqlite3.connect(db_path)
```

2024-09-24 06:44 UTC, KenyuKurimoto submitted a review, later dismissed

2024-09-24 08:59 UTC, KenyuKurimoto commented
@h-wata 
こちらのリポジトリについても追って規格との齟齬が無いかの確認を実施するので、いったんマージしてしまってください。

2024-09-24 23:45 UTC, h-wata approved these changes

2024-09-24 23:45 UTC, merged